DEBUG 2023-04-07 20:44:47.652 UTC: 	 CRAB Client version: v3.230124
DEBUG 2023-04-07 20:44:47.652 UTC: 	 Running on: Linux naf-cms13.desy.de 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-04-07 20:44:47.652 UTC: 	 Executing command: 'checkwrite'
DEBUG 2023-04-07 20:44:47.652 UTC: 	 Could not find CRAB cache file /afs/desy.de/user/b/beozek/.crab3; creating a new one.
DEBUG 2023-04-07 20:44:47.654 UTC: 	 Checking credentials
DEBUG 2023-04-07 20:44:47.654 UTC: 	 Proxy file /tmp/x509up_u39853 not found
DEBUG 2023-04-07 20:44:47.654 UTC: 	 Creating new proxy for 172:00 hours
DEBUG 2023-04-07 20:44:47.654 UTC: 	 Executing command :
 voms-proxy-init --rfc --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem --out /tmp/x509up_u39853 --valid 192:00 --voms cms:/cms
DEBUG 2023-04-07 20:44:48.388 UTC: 	 output : 
 error: 
 retcode : 1
ERROR 2023-04-07 20:44:48.389 UTC: 	 

ERROR 2023-04-07 20:44:48.389 UTC: 	 Error executing voms-proxy-init --rfc --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem --out /tmp/x509up_u39853 --valid 192:00 --voms cms:/cms:


ERROR 2023-04-07 20:44:48.389 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/checkwrite.py", line 20, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 355, in __init__
    self.handleVomsProxy(proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/Commands/SubCommand.py", line 461, in handleVomsProxy
    proxyOptsSetPlace=proxyOptsSetPlace)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/CredentialInteractions.py", line 103, in createNewVomsProxy
    proxy.create()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230124.00/lib/CRABClient/ProxyInteractions.py", line 52, in create
    raise ProxyCreationException(msg)
ProxyCreationException: Error executing voms-proxy-init --rfc --cert ~/.globus/usercert.pem --key ~/.globus/userkey.pem --out /tmp/x509up_u39853 --valid 192:00 --voms cms:/cms:


INFO 2023-04-07 20:44:48.392 UTC: 	 Log file is /nfs/dust/cms/user/beozek/EFT/CMSSW_10_6_27/src/crab.log
